/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Mark } from './mark';

export class Faculty {
    id?: number;
    name?: string;
    universityName?: string;
    address?: string;
    description?: string;
    markList?: Array<Mark>;
}
